### ISSUE TITLE
package raft-0.22.0-1 conflicts with dqlite < 1.16.0-2 provided by dqlite-1.16.0-0.2 from @System  (on Fedora 39)

### ISSUE THREAD

**Issue by sebd71** [ganto/copr-lxc4#44] opened 2024-03-25 14:18 UTC
Since this yesterday (2024-03-25), I encounter the following error.
Any idea how to way out of this situation ? 

```
~$ dnf update --ref
...

 Problem: package raft-0.22.0-1.fc39.x86_64 from updates conflicts with dqlite < 1.16.0-2 provided by dqlite-1.16.0-0.2.fc39.x86_64 from @System
  - cannot install the best update candidate for package raft-0.22.0-0.1.fc39.x86_64
  - cannot install the best update candidate for package dqlite-1.16.0-0.2.fc39.x86_64
====================================================================================================================
 Package                Architecture             Version                            Repository                 Size
====================================================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 raft                   x86_64                   0.22.0-1.fc39                      updates                   105 k

Transaction Summary
====================================================================================================================
Skip  1 Package


~$ dnf info raft
Last metadata expiration check: 0:01:06 ago on lun. 25 mars 2024 15:14:11.
Installed Packages
Name         : raft
Version      : 0.22.0
Release      : 0.1.fc39
Architecture : x86_64
Size         : 223 k
Source       : raft-0.22.0-0.1.fc39.src.rpm
Repository   : @System
From repo    : copr:copr.fedorainfracloud.org:ganto:lxc4
Summary      : C implementation of the Raft consensus protocol
URL          : https://raft.readthedocs.io/
License      : LGPL-3.0-only WITH LGPL-3.0-linking-exception
Description  : Fully asynchronous C implementation of the Raft consensus protocol. It consists
             : of a core part that implements the core Raft algorithm logic and a pluggable
             : interface defining the I/O implementation for networking and disk persistence.

Available Packages
Name         : raft
Version      : 0.22.0
Release      : 1.fc39
Architecture : x86_64
Size         : 105 k
Source       : raft-0.22.0-1.fc39.src.rpm
Repository   : updates
Summary      : C implementation of the Raft consensus protocol
URL          : https://raft.readthedocs.io/
License      : LGPL-3.0-only WITH LGPL-3.0-linking-exception
Description  : Fully asynchronous C implementation of the Raft consensus protocol. It consists
             : of a core part that implements the core Raft algorithm logic and a pluggable
             : interface defining the I/O implementation for networking and disk persistence.

Name         : raft
Version      : 0.22.0
Release      : 0.1.fc39
Architecture : src
Size         : 378 k
Source       : None
Repository   : copr:copr.fedorainfracloud.org:ganto:lxc4
Summary      : C implementation of the Raft consensus protocol
URL          : https://raft.readthedocs.io/
License      : LGPL-3.0-only WITH LGPL-3.0-linking-exception
Description  : Fully asynchronous C implementation of the Raft consensus protocol. It consists
             : of a core part that implements the core Raft algorithm logic and a pluggable
             : interface defining the I/O implementation for networking and disk persistence.

Name         : raft
Version      : 0.22.0
Release      : 1.fc39
Architecture : i686
Size         : 116 k
Source       : raft-0.22.0-1.fc39.src.rpm
Repository   : updates
Summary      : C implementation of the Raft consensus protocol
URL          : https://raft.readthedocs.io/
License      : LGPL-3.0-only WITH LGPL-3.0-linking-exception
Description  : Fully asynchronous C implementation of the Raft consensus protocol. It consists
             : of a core part that implements the core Raft algorithm logic and a pluggable
             : interface defining the I/O implementation for networking and disk persistence.


~$ dnf info dqlite
Fedora 39 - x86_64 - Updates                                                                                                                                                                                 28 kB/s |  18 kB     00:00    
Fedora 39 - x86_64 - Updates                                                                                                                                                                                1.6 MB/s | 2.5 MB     00:01    
Last metadata expiration check: 0:00:08 ago on lun. 25 mars 2024 15:14:11.
Installed Packages
Name         : dqlite
Version      : 1.16.0
Release      : 0.2.fc39
Architecture : x86_64
Size         : 207 k
Source       : dqlite-1.16.0-0.2.fc39.src.rpm
Repository   : @System
From repo    : copr:copr.fedorainfracloud.org:ganto:lxc4
Summary      : Embeddable, replicated and fault tolerant SQL engine
URL          : https://github.com/canonical/dqlite
License      : LGPL-3.0-only WITH LGPL-3.0-linking-exception
Description  : dqlite is a C library that implements an embeddable and replicated SQL database
             : engine with high-availability and automatic failover.

Available Packages
Name         : dqlite
Version      : 1.15.1
Release      : 1.fc39
Architecture : i686
Size         : 101 k
Source       : dqlite-1.15.1-1.fc39.src.rpm
Repository   : fedora
Summary      : Embeddable, replicated and fault tolerant SQL engine
URL          : https://github.com/canonical/dqlite
License      : LGPL-3.0-only WITH LGPL-3.0-linking-exception
Description  : dqlite is a C library that implements an embeddable and replicated SQL database
             : engine with high-availability and automatic failover.

Name         : dqlite
Version      : 1.16.0
Release      : 0.2.fc39
Architecture : src
Size         : 231 k
Source       : None
Repository   : copr:copr.fedorainfracloud.org:ganto:lxc4
Summary      : Embeddable, replicated and fault tolerant SQL engine
URL          : https://github.com/canonical/dqlite
License      : LGPL-3.0-only WITH LGPL-3.0-linking-exception
Description  : dqlite is a C library that implements an embeddable and replicated SQL database
             : engine with high-availability and automatic failover.

```

**Comment by ganto** [comment] 2024-03-25 21:44
Actually my idea was to push `dqlite-1.16.0-2` (which would correspond to `dqlite-1.16.0-0.2` in COPR) to Fedora. But for an unknown reason `dqlite-1.16.0` cannot build successfully anymore in Fedora. Looking into it...

**Comment by ganto** [comment] 2024-03-25 23:06
I just pushed `dqlite-1.16.4-0.1` to COPR. My first tests showed that this "should" be a drop-in replacement for `dqlite-1.16.0` meaning that it doesn't include any changes that would require a rebuild of LXD. Also it gets rid of the dependency to `raft` which is the cause of the dependency issue you're seeing. `raft` will only be required as a separate library if you're (also) using Incus.

Maybe give me a short feedback if the update to `dqlite-1.16.4` solved the issue for you. Then I'll push this also to the Fedora repositories.

**Comment by sebd71** [comment] 2024-03-26 08:20
Yes, thanks a lot you can close this issue.
At least problem is solved on my host / F39 after updating with your latest build :

```
====================================================================================================================
 Package       Arch     Version                                   Repository                                   Size
====================================================================================================================
Upgrading:
 dqlite        x86_64   1.16.4-0.1.fc39                           copr:copr.fedorainfracloud.org:ganto:lxc4   163 k
 raft          x86_64   0.22.0-1.fc39                             updates                                     105 k

Transaction Summary
====================================================================================================================
Upgrade  2 Packages
```

About build failure result in copr, it seems just due to an error on F38 in testsuite for libdqlite :
```
membership/transferAndSqlExecWithBarrier                    [ ERROR ]
Error: test/integration/test_membership.c:291: assertion failed: rv == DQLITE_CLIENT_PROTO_ERROR (1 == 3)
Error: child killed by signal 6 (Aborted)
membership/transferPendingTransaction  
```

But I don't really know why this test fail.

**Comment by ganto** [comment] 2024-03-28 23:48
Yes, the test suite is quite flaky on the Fedora build infrastructure. After a few retries the test suite eventually succeeded.

I'm closing this issue. The issues with the Fedora packages (when being used without this COPR repo) are further tracked in Red Hat Bugzilla [2270048](https://bugzilla.redhat.com/show_bug.cgi?id=2270048) and [2270051](https://bugzilla.redhat.com/show_bug.cgi?id=2270051).

**Closed by ganto** 2024-03-28 23:48 UTC
