### ISSUE TITLE
Known issue with version 4 on CentOS 8

### ISSUE THREAD

**Issue by resdigita** [ganto/copr-lxc4#1] opened 2020-04-06 08:10 UTC
I was just happy to notice that work on version 4 has begun.  I would like to point out a **permission issue** that exists with versions 3.18, 3.21 and 4.0 installed in **CentOS 8**.
If you create a CentOS 8 container and install Postfix, Postfix cannot be started afterwards. 
```
...systemd[1]: Starting Postfix Mail Transport Agent...
... postfix[86]: /usr/libexec/postfix/postfix-script: line 127: /dev/null: Permission denied
... postfix/postfix-script[93]: fatal: the Postfix mail system is already running
```

For this I had posted a topic at linuxcontainers.org, see https://discuss.linuxcontainers.org/t/postfix-doesnt-run-in-an-lxd-fedora-31-container-permission-denied/7221

I had installed snap as a test and was able to reproduce the problem with version 3.21 as well as with 4.0. With Fedora 31 the problem did not occur (with version 4.0, version 3.21 did not run at al with snap).

The problem did not occur with CentOS 7. 

Unfortunately I'm not familiar with go, and have no idea how to narrow down the problem more precisely.

**Comment by ganto** [comment] 2020-04-06 22:38
Thanks for the input. I'll have a closer look when I start testing these packages.

**Comment by ganto** [comment] 2020-09-11 20:22
I cannot reproduce it on a plain Fedora host with the current packages from [ganto/lxc4 COPR](https://copr.fedorainfracloud.org/coprs/ganto/lxc4):
```
$ lxc info | egrep "(driver|os|server)_version"
  driver_version: 4.0.4
  os_version: "31"
  server_version: "4.5"
$ lxc launch images:fedora/31 f31
Creating f31
Starting f31
$ lxc shell f31
# dnf install -y postfix
# systemctl start postfix
# systemctl status postfix
● postfix.service - Postfix Mail Transport Agent
   Loaded: loaded (/usr/lib/systemd/system/postfix.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-09-11 20:21:15 UTC; 13ms ago
  Process: 243 ExecStartPre=/usr/libexec/postfix/aliasesdb (code=exited, status=0/SUCCESS)
  Process: 247 ExecStartPre=/usr/libexec/postfix/chroot-update (code=exited, status=0/SUCCESS)
  Process: 248 ExecStart=/usr/sbin/postfix start (code=exited, status=0/SUCCESS)
 Main PID: 316 (master)
    Tasks: 3 (limit: 9368)
   Memory: 6.8M
      CPU: 480ms
   CGroup: /system.slice/postfix.service
           ├─316 /usr/libexec/postfix/master -w
           ├─317 pickup -l -t unix -u
           └─318 qmgr -l -t unix -u

Sep 11 20:21:14 f31 systemd[1]: Starting Postfix Mail Transport Agent...
Sep 11 20:21:14 f31 postfix/postfix-script[314]: starting the Postfix mail system
Sep 11 20:21:15 f31 postfix/master[316]: daemon started -- version 3.4.17, configuration /etc/postfix
Sep 11 20:21:15 f31 systemd[1]: Started Postfix Mail Transport Agent.
```
Since don't plan to do any CentOS packages for LXD 4 for now, I'm closing this issue.

**Closed by ganto** 2020-09-11 20:22 UTC
